[project]
name = "notely"
version = "0.2.0"
dependencies = [
    "torch==1.10.1",
    "torchvision==0.11.2",
    "torchaudio==0.10.1",
    "openai-whisper",
    "ollama",
    "numpy==1.26.4",
    "halo"
]
authors = [
    {name = "TheWorldJar", email = "theworldjar@protonmail.com"}
]
description = "Create transcripts from audio files and process thoses transcripts to create notes!"
requires-python = ">= 3.9"
[project.optional-dependencies]
dev = [
    "pytest"
]